name: Lint
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    uses: tryghost/actions/.github/workflows/lint-only.yml@dae5741511aa11829af5b22226804ed767fb6ff2 # main
