name: Lint
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    uses: tryghost/actions/.github/workflows/lint-only.yml@2ad8c9a006b0f0b320bfb8c935706b645ca9409c # main
